#include "helper.h"
#include "visualLB.h"
#include "LBDefinitions.h"
#include "computeCellValues.h"
#include <stdio.h>

void write_vtkPointCoordinates( FILE *fp, int *xlength)
{
  double originX = 0.0;
  double originY = 0.0;
  double originZ = 0.0;

  for(int z = 0; z < xlength[2] + 2; ++z){
    for(int y = 0; y < xlength[1] + 2; ++y) {
      for(int x = 0; x < xlength[0] + 2; ++x) {
        fprintf(fp, "%f %f %f \n", originX+x, originY+y, originZ+z);
      }
    }
  }
}

void write_vtkHeader( FILE *fp, int *xlength )
{

	fprintf(fp,"# vtk DataFile Version 2.0\n");
	fprintf(fp,"generated by CFD-lab course output\n");
	fprintf(fp,"ASCII\n");
	fprintf(fp,"\n");
	fprintf(fp,"DATASET STRUCTURED_GRID\n");
	fprintf(fp,"DIMENSIONS  %i %i %i \n", xlength[0] + 2, xlength[1] + 2, xlength[2] + 2);
	fprintf(fp,"POINTS %i float\n", (xlength[0] + 2)*(xlength[1] + 2)*(xlength[2] + 2) );
	fprintf(fp,"\n");
}

void writeVtkOutput(const double * const collideField, const int * const flagField,
		const char * filename, unsigned int t, int *xlength)

{
 
  char szFileName[80];
  double density=0.0;
  double velocity[3] = {0.0,0.0,0.0};

  FILE *fp=NULL;
  /* Save filename as a combination of passed filename and timestep */
  sprintf( szFileName, "%s.%i.vtk","lbm_", t );
  fp = fopen( szFileName, "w");
  if( fp == NULL )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR( szBuff );
    return;
  }


  write_vtkHeader( fp, xlength );

  write_vtkPointCoordinates( fp, xlength);

  fprintf(fp,"POINT_DATA %i \n", (xlength[0] + 2)*(xlength[1] + 2)*(xlength[2] + 2) );
  fprintf(fp,"\n");
  fprintf(fp, "VECTORS velocity float\n");
  for(int z = 0; z < xlength[2] + 2; ++z) {
    for(int y = 0; y < xlength[1] + 2; ++y) {
      for(int x = 0; x < xlength[0] + 2; ++x) {
	density=0.0;
    velocity[0]=0; velocity[1] =0; velocity[2]= 0;
    /* Compute (macroscopic) velocities */
    computeDensity(&collideField[idx(xlength, x, y, z, 0)], &density);
    computeVelocity(&collideField[idx(xlength, x, y, z, 0)], &density,velocity);
	fprintf(fp, "%f %f %f\n", velocity[0], velocity[1], velocity[2]);
      }
    }
  }
  /* Compute density for each cell */
  fprintf(fp,"\n");
  fprintf(fp, "SCALARS density float 1\n");
  fprintf(fp, "LOOKUP_TABLE default \n");
  for(int z = 0; z < xlength[2] + 2; ++z) {
    for(int y = 0; y < xlength[1] + 2; ++y) {
      for(int x = 0; x < xlength[0] + 2; ++x) {
	density=0.0;
    computeDensity(&collideField[idx(xlength, x, y, z, 0)], &density);
        fprintf(fp, "%f\n", density );
      }
    }
  }

  if( fclose(fp) )
  {
    char szBuff[80];
    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );
  }

}
